### ISSUE TITLE
Svg containers

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/web#33]
## Задача

Уменьшить контейнеры у логотипов до размеров гексагона

## Материалы

Контейнер у свг сильно больше размеров самой свг

![image](https://user-images.githubusercontent.com/62806448/158014443-98f5424e-afa3-4b3a-86b7-977d391b0977.png)

На сайте в изначальном состоянии контейнер режет иконку (по бокам):

https://user-images.githubusercontent.com/62806448/158019547-724ec378-4671-4968-85d3-e3a1e3a368b3.mov

## Иконки

[Archive.zip](https://github.com/torin-asakura/web/files/8237455/Telegram.Archive.zip)

**Comment by wolfoel** [comment]
Обрезала под 0. [Icons_Hex.Archive.zip](https://github.com/torin-asakura/web/files/8238459/Icons_Hex.Archive.zip)
Вообще не пойму почему у вас такой огромный контейнер, у меня везде открывается максимум на 5 пикселей больше гекса🧐🧐🧐
